version: "3.9"

services:
  app:
    build: .
    container_name: portfolio_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # - ./node_modules:/app/node_modules
      - ./src:/app/src